// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNs3MOOuRcStnMSAFxl_0e82d9SDa9ss',
    appId: '1:83267947231:web:f32fefceea8a0aef17f76a',
    messagingSenderId: '83267947231',
    projectId: 'dogdatabase-fe422',
    authDomain: 'dogdatabase-fe422.firebaseapp.com',
    storageBucket: 'dogdatabase-fe422.firebasestorage.app',
    measurementId: 'G-V4XC0W61Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn8Y_4xfw1YiYr3x35FD9GfODkF0OyQxU',
    appId: '1:83267947231:android:e22a84b23ca8a53317f76a',
    messagingSenderId: '83267947231',
    projectId: 'dogdatabase-fe422',
    storageBucket: 'dogdatabase-fe422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNRHKDDLDaqmc_xsxwLPSfwASunv-qex8',
    appId: '1:83267947231:ios:ba4ffdeeace76a4e17f76a',
    messagingSenderId: '83267947231',
    projectId: 'dogdatabase-fe422',
    storageBucket: 'dogdatabase-fe422.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNRHKDDLDaqmc_xsxwLPSfwASunv-qex8',
    appId: '1:83267947231:ios:ba4ffdeeace76a4e17f76a',
    messagingSenderId: '83267947231',
    projectId: 'dogdatabase-fe422',
    storageBucket: 'dogdatabase-fe422.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNs3MOOuRcStnMSAFxl_0e82d9SDa9ss',
    appId: '1:83267947231:web:200b2b45adffe06f17f76a',
    messagingSenderId: '83267947231',
    projectId: 'dogdatabase-fe422',
    authDomain: 'dogdatabase-fe422.firebaseapp.com',
    storageBucket: 'dogdatabase-fe422.firebasestorage.app',
    measurementId: 'G-J6X9XH6C46',
  );

}